script: bash ./deploy_gh_pages.sh
env:
  global:
  - GH_REF: github.com/BangKarlsen/noopad.git
  - secure: "nhG4vqeKSkPFyP7DDr7NaW7G43L72BAszoKubRFCTlp7s+k1+v9/McxYjoLylUirFKLh8kboAVnc56Ha57ImoGF11X0KU0AtoWn+RozMDOU9Q3qQEhQ9pzvfXBEOW+DEmpjxCfQEo+9rAWhHfiLwvL4Yv8ueR0Phnv3VB/j9/ntcwF1ojZQIsL1ag6lNC92hkQjzpybRZpjjSbD0qHZECCbQAE5acwoRQFN0qnRp5DTwRmmlPKly8ZN/MWyjWa3paKDF4+F8RNWKHwFd6MCFtTRvLrKMbAhqewpBfG5rxcOSTBtxu3+zVuEx1A4k2SSJLIpqKAXMfwDoJ4mVgil7QzLOY5n2X+9zi1ER3hKUt7BozuFhfCc+WTpgu2nkihr1TG5uysicqP7nOvsbJ4DZ2TLpbISxkK4pJKyK19RsgN03V41+Nhd53+VKn98fujunLLBumY8Q9K9Mfk4gR691SJbgPrV1lCEtPS3TBDbCJ5HCTJHv4sAZNU2qbPJQs5kKewMbJlbzhA6etb9pPMuKnO+kNK2EDyJLRKu43EsgZ+llmXDAJrOr9R8Zpzjb1EoLSN+lagNlOGNW6Hcwl3bd2CiGoPJU1v7VCzxxKWBQfaV2yn0feosRXLlYcqe/pG8EvECUeAe8//Z2mj7fcRv2r0+Zm7DWu6W+lsDEY7oc9lg="
language: node_js
node_js:
  - "0.10"
